YAIP/lab_12/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "view", to: "home#view"
  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
end

YAIP/lab_12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

YAIP/lab_12/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

YAIP/lab_12/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

YAIP/lab_12/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:view]
  before_action :assertion, only: [:view]
  def index
  end

  def assertion
    n, m = params[:n].to_i, params[:m].to_i
    if (n.zero? || n.nil?) || (m.zero? || m.nil?)
      flash[:alert] = 'You cannot enter zeroes or nil values!, try again'
      redirect_to action: :index and nil
    end
  end

  def view
    @nod = calculate
    @nok = (params[:n].to_i * params[:m].to_i) / calculate
    @n = params[:n].to_i
    @m = params[:m].to_i
    puts params.inspect
    render partial: 'view'
  end

  private

  def calculate
    n = params[:n].to_i
    m = params[:m].to_i
    n, m = m, n % m while m != 0
    n
  end

end

YAIP/lab_12/app/helpers/application_helper.rb
module ApplicationHelper
end

YAIP/lab_12/app/helpers/home_helper.rb
module HomeHelper
end

YAIP/lab_12/app/views/home/_view.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container text-center mb-3">
  <h1>LABA12</h1>
  <p>Results</p>
</div>

<div class="d-flex justify-content-center">
  <div class="d-inline-block">
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>
            Number N
          </th>
          <th>
            Number M
          </th>
          <th>
            NOD
          </th>
          <th>
            NOK
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= @n %></td>
          <td><%= @m %></td>
          <td><%= @nod %></td>
          <td><%= @nok %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-3">
  <%= link_to "Repeat calculation", :home_index, class: "btn btn-primary" %>
</div>

YAIP/lab_12/app/views/home/index.html.erb
<div class="d-flex justify-content-center">
  <%= form_with url: view_path, method: :post, local: true do %>
    <div class="input-group mb-3">
      <label for="numberN" class="input-group-text">Number N:</label>
      <input type="number" name="n" id="numberN" class="form-control">
    </div>

    <div class="input-group mb-3">
      <label for="numberM" class="input-group-text">Number M:</label>
      <input type="number" name="m" id="numberM" class="form-control">
    </div>

    <div class="d-flex justify-content-center mt-3">
      <%= submit_tag 'Calculate', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

YAIP/lab_12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Lab12</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application" %>

</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">LABA12</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link me-2" href="#">Welcome <%= current_user.email %></a>
          </li>
          <li class="nav-item">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-info me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
          </li>
      <%elsif !user_signed_in? && controller_name == 'home'%>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-3">
  <% unless notice.nil? %>
    <div class="alert alert-success ">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>


  <%= yield %>
</div>
</body>
</html>