YAIP/lab_11/config/routes.rb
Rails.application.routes.draw do
  get 'calc/input'
  get 'calc/view'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/get_xml', to: 'calc#get_xml', as: 'get_xml'
  # Defines the root path route ("/")
  # root "posts#index"
  root "calc#input"
end

YAIP/lab_11/app/models/result.rb
class Result < ApplicationRecord
  validates :n, uniqueness: { scope: :m }
end

YAIP/lab_11/app/controllers/calc_controller.rb
class CalcController < ApplicationController
  before_action :assertion, only: [:view]

  def input; end

  def assertion
    n = params[:n].to_i
    m = params[:m].to_i
    if n.zero? || m.zero?
      flash[:alert] = 'You cannot enter zeroes or nil values!, try again'
      redirect_to action: :input
    end
  end

  def get_xml
    @results = Result.all
    hash_array = Array.new

    @results.each do |record|
      hash_string = { "n" => record.n, "m" => record.m, "nok" => record.nok, "nod" => record.nod }
      hash_array.push(hash_string)
    end

    file_path = create_xml_file(hash_array.to_xml)
    send_file file_path, type: 'application/xml', disposition: 'inline'
  end

  def view
    @n = params[:n].to_i
    @m = params[:m].to_i

    is_record_found = false
    db_records = Result.all
    db_records.each do |record|
      if record.n == @n && record.m == @m
        @nod = record.nod
        @nok = record.nok
        is_record_found = true
        puts "found record of n: #{@n} and m: #{@m}, loading from db"
        return
      end
    end

    unless is_record_found
      @nod = calculate
      @nok = (params[:n].to_i * params[:m].to_i) / calculate
      puts "no record found of n: #{@n} and m: #{@m}, calculating and saving to db"
      record_to_save = Result.new(n: @n, m: @m, nod: @nod, nok: @nok)
      record_to_save.save
    end
  end

  def create_xml_file(xml_text)
    file_path = Rails.root.join('public', 'result.xml')
    File.open(file_path, 'w') do |file|
      file.write(xml_text)
    end
    file_path
  end

  private

  def calculate
    n = params[:n].to_i
    m = params[:m].to_i
    n, m = m, n % m while m != 0
    n
  end
end

YAIP/lab_11/app/helpers/calc_helper.rb
module CalcHelper
end

YAIP/lab_11/app/views/calc/input.html.erb
<div class="container text-center">
  <h1>LABA11</h1>
  <p>Input two numbers</p> <br>
</div>

<div class="d-flex justify-content-center">
  <%= form_tag("/calc/view", method: "get", class: "mb-3") do %>
    <div class="input-group mb-3">
      <span class="input-group-text">Number N:</span>
      <%= number_field_tag(:n, nil, class: "form-control", "aria-label": "Number N") %>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text">Number M:</span>
      <%= number_field_tag(:m, nil, class: "form-control", "aria-label": "Number M") %>
    </div>

    <div class="d-flex justify-content-center mt-3">
      <%= submit_tag("Calculate result, show as default", name: "calculate_default",class: "btn btn-primary me-2") %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center mt-2">
  <%= link_to("View database as xml", get_xml_path, class: "btn btn-secondary") %>
</div>

YAIP/lab_11/app/views/calc/view.html.erb
<div class="container text-center mb-3">
  <h1>LABA11</h1>
  <p>Results</p>
</div>

<div class="d-flex justify-content-center">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>
          Number N
        </th>
        <th>
          Number M
        </th>
        <th>
          NOD
        </th>
        <th>
          NOK
        </th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @n %></td>
        <td><%= @m %></td>
        <td><%= @nod %></td>
        <td><%= @nok %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="d-flex justify-content-center mt-3">
  <%= link_to "Repeat calculation", :calc_input, class: "btn btn-primary" %>
</div>

YAIP/lab_11/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Lab11</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application" %>

</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<% flash.each do |msg| %>
  <%= content_tag(:div, msg[1], class: "alert alert-danger") %>
<% end %>

<%= yield %>
</body>
</html>